### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by zaranah** [zaranah/protospace-37400#1]
# URL
https://protospace-37400.herokuapp.com/

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから削除ボタンをクリックすると、プロトタイプを削除できるようにしましょう**
以下のエラーページに遷移してしまい削除できません。
<img width="678" alt="スクリーンショット 2022-01-18 9 10 11" src="https://user-images.githubusercontent.com/62644781/149849998-343907be-796a-4d1d-b4da-d4b45b59341d.png">

- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
プロトタイプ一覧、プロトタイプ詳細ページ、コメントの投稿者名をクリックしたときに正しく遷移しません。（別のユーザーの詳細ページやエラーページに遷移してしまう場合があります。）

- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるようにしましょう**
ユーザー名が表示されていません。
<img width="678" alt="スクリーンショット_2022-01-18_9_10_55" src="https://user-images.githubusercontent.com/62644781/149850025-f2ce043f-ea71-4696-9b34-31652eda0532.png">

- [x] **ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、ログインページにリダイレクトされるようにしましょう**
プロトタイプ編集ページに遷移しようとすると、トップページにリダイレクトされてしまいます。

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるようにしましょう**
他のユーザーのプロトタイプ編集ページに遷移できてしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by zaranah** [comment]
まだ一つ目しか確認できていないのですが、localhostではうまくいって、提出された方ではエラーが出る現象が発生しています。
こちらHerokuの方法が間違っているのでしょうか。
ご返信いただけますと幸いです。

**Comment by mo1015** [comment]
ご提出ありがとうございます！

マージやデプロイはお済みでしょうか？
ローカル環境ではなく、本番環境に反映されているか動作確認をしてから提出をお願いいたします。
※デプロイに関して不明点がありましたら、テックコネクトにてご相談ください。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by zaranah** [comment]
修正完了しました。
ご確認のほど、よろしくお願いいたします。

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、引き続き修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
①プロトタイプ詳細ページの投稿者名をクリックしたとき、正しく遷移しません。（別のユーザーの詳細ページか、エラーページに遷移してしまいます。）
②コメントの投稿者名をクリックしたとき、正しく遷移しません。（そのプロトタイプを投稿したユーザーの詳細ページに遷移してしまいます。）

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by zaranah** [comment]
何度も失礼いたしました。
修正完了しました。
ご確認のほど、よろしくお願いいたします。

**Comment by mo1015** [comment]
ご提出ありがとうございます！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう！
